### ISSUE TITLE
Could not find a package configuration file provided by "GTest"

### ISSUE THREAD

**Issue by sonichy** [PikachuHy/QtMarkdown#3]
CMake Error at test/CMakeLists.txt:2 (find_package):
  Could not find a package configuration file provided by "GTest" with any of
  the following names:

    GTestConfig.cmake
    gtest-config.cmake

  Add the installation prefix of "GTest" to CMAKE_PREFIX_PATH or set
  "GTest_DIR" to a directory containing one of the above files.  If "GTest"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

**Comment by PikachuHy** [comment]
please install gtest. 

https://github.com/google/googletest

for example, in windows
```
vcpkg.exe install gtest
```

**Comment by sonichy** [comment]
How to install on Linux ？
Why text editor need gtest ?

**Comment by PikachuHy** [comment]
The gtest is just a test framework used for unit test.
you can ignore 
https://github.com/PikachuHy/QtMarkdown/blob/ff18d20a50ce49eb6a5de5c84d0a02391e745363/CMakeLists.txt#L34

**Comment by sonichy** [comment]
注释 test 后跑起来了，QtMarkdownEditorMain 没有菜单不能编辑，双击 QtMarkdown 生成了html。

**Comment by PikachuHy** [comment]
The Editor is still under development.
The Parser is almost complete.
