### ISSUE TITLE
Can you please add a license?

### ISSUE THREAD

**Issue by nuttyartist** [PikachuHy/QtMarkdown#5]
Hi! Very interesting project!

1. Integrating QtMarkdown into our open-source note-taking app Notes (https://github.com/nuttyartist/notes) will be very cool. But it's impossible to do so unless you provide a license. Hopefully, a permissive one (eg, MIT, Apache).
2. I want to try the examples but I'm getting these errors:

![Screen Shot 2023-04-17 at 11 59 28 AM](https://user-images.githubusercontent.com/16375940/232436870-1df83d34-d7ed-48d6-a3ef-e830b5ee3967.png)

Thanks!

**Comment by PikachuHy** [comment]
I will check it on weekend.

**Comment by nuttyartist** [comment]
Thanks for adding a license! I appreciate that.

I'm now getting the following errors:

![Screen Shot 2023-05-02 at 5 04 15 PM](https://user-images.githubusercontent.com/16375940/235690381-0063cbde-1896-4949-a1aa-88e9d11b5ccc.png)

I would really like to test QtMarkdown.

**Comment by PikachuHy** [comment]
run and try again
```
git submodule update --init
```

**Comment by nuttyartist** [comment]
I did:

```
git clone --recursive https://github.com/PikachuHy/QtMarkdown.git
git submodule update --init
```

Then, I opened `QtMarkdown/CMakeLists.txt` using QtCreator, and these are the errors I get now:
![Screen Shot 2023-05-03 at 8 01 42 PM](https://user-images.githubusercontent.com/16375940/235987761-38f8258b-4428-4252-bdf4-81653bdf6977.png)

Am I doing something wrong?

**Comment by PikachuHy** [comment]
I updated the 3rd dependency.
git pull and try again

**Comment by nuttyartist** [comment]
Yay, it compiles now! But the example doesn't compile. I added this to the `example/CMakeLists.txt` 
```cmake
cmake_minimum_required(VERSION 3.20)
```
 But then I get:

![Screen Shot 2023-05-05 at 4 06 51 PM](https://user-images.githubusercontent.com/16375940/236465584-0d931049-d8b4-4fe5-b11e-8890b4e36748.png)

if I comment it out I get:

![Screen Shot 2023-05-05 at 4 07 21 PM](https://user-images.githubusercontent.com/16375940/236465702-a857e249-e401-48c7-9e0d-5f8747cb508e.png)

Thanks for having the patience for working this out with me.

**Comment by PikachuHy** [comment]
I can't reproduce this problem.

```
git clone https://github.com/PikachuHy/QtMarkdown.git
cd QtMarkdown
git submodule update --init
mkdir build && cd build
# e.g. -DCMAKE_PREFIX_PATH=/Users/pikachu/Qt/6.5.0/macos/lib/cmake
cmake .. -DCMAKE_PREFIX_PATH=/path/to/your/Qt/lib/cmake
make -j
```

```
➜  build git:(master) tree example -L 1
example
├── CMakeFiles
├── Makefile
├── QtMarkdownParserExample
├── QtMarkdownParserExample_autogen
├── QtQuickMarkdownEditorExample
├── QtQuickMarkdownEditorExample_autogen
├── QtWidgetMarkdownEditorExample
├── QtWidgetMarkdownEditorExample_autogen
└── cmake_install.cmake

4 directories, 5 files
➜  build git:(master)
```

**Comment by nuttyartist** [comment]
Great, it's working now! This is very cool, @PikachuHy. It's still very rough around the edges - selection doesn't work well, it crashes many times, and some markdown formatting like bold, italics etc is not implemented yet. But overall, it's very promising.

Can you tell me, is that a complete re-writing of a text editor implemented from scratch, or are you parsing Markdown, converting it into HTML, and then letting QTextEdit render it? It seems to me like the former, but I would like to make sure.

**Comment by PikachuHy** [comment]
yes，it is complete re-writing of a text editor implemented from scratch.

**Comment by PikachuHy** [comment]
I write a new Markdown parser.
and draw all markdown elements by QPainter.

**Comment by PikachuHy** [comment]
Many features are not implemented and the editor is not well polished.

**Comment by PikachuHy** [comment]
> it crashes many times

submit another issue with test case，I will fix it.

**Comment by nuttyartist** [comment]
> I write a new Markdown parser. and draw all markdown elements by QPainter.

That's very impressive.

> submit another issue with test case，I will fix it.

Great, I will.

I will close this issue now.
